In [1]:
import numpy as np

In [2]:
myarr = np.array([1, 2, 3, 4, 5])  # Creating NumPy array

myarr

array([1, 2, 3, 4, 5])

In [3]:
myarr2 = np.array([[1, 2, 3, 4, 5]], np.int8)  # Specifying the number of bytes that the array element can have. In this case 8 byte

myarr2

array([[1, 2, 3, 4, 5]], dtype=int8)

In [4]:
myarr[0]  # Acessing elements of 1-D Array

np.int64(1)

In [5]:
# myarr[0, 0]  # Acessing elements of 2-D Array
myarr2[0][1]  # Another way of accessing elements of 2-D array

np.int8(2)

In [6]:
myarr.ndim  # Checking Array dimensions


1

In [7]:
myarr2.ndim

2

In [8]:
myarr3 = np.array([2, 4, 6, 8], ndmin=5)  # Defining the number of dimensions in array using "ndmin" argument

myarr3

array([[[[[2, 4, 6, 8]]]]])

In [9]:
myarr3.ndim

5

In [10]:
# myarr[1:4]  # First parameter specifies start position, second parameter specifies stop position
# myarr[:]  # When start and end position is not specified then it returns all
# myarr[:4]
# myarr[1:]
myarr[::2]  # Third parameter specifies step

array([1, 3, 5])

In [11]:
arr = np.array([
    [1, 2, 3],
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
# arr[1]
# arr[::]
# arr[1][1:3]  # First square bracket for rows and second square bracket for column
arr[1][1:5]  # Even though column specified goes beyond the range it doesn't give any error

array([12, 13])

In [12]:
arr2 = np.array(["Roshan", "Rahul", "Rakesh", 1, 2, 1.1, 2.2])

arr2.dtype  # Returns the data type of the array

dtype('<U32')

In [13]:
arr3 = np.array([1, 2, 3, 4, 5], dtype='S')  # Creating arrays with defined data types

print(arr3.dtype)

|S1


In [14]:
# newarr = np.float16(arr3)  # Converting numpy array data type using functions
newarr = arr3.astype(float)  # Converting numpy array data type using "astype()" function

print(newarr.dtype)

float64


In [15]:
check = np.array([-1, 0])
ansCheck = check.astype(bool)
print(ansCheck)

[ True False]


In [16]:
# x = arr2[3:6]  # Default method is view (i.e; "arr2.view()"  ). Changes is also made in original array in case of "view()"
x = arr2[3:6].copy()  # Changes is not made in original array in case of "copy()"
x[:] = 0  
print(x)
print(arr2)

['0' '0' '0']
['Roshan' 'Rahul' 'Rakesh' '1' '2' '1.1' '2.2']


In [17]:
print(myarr3.shape)  # Returns a tuple with each index having the number of corresponding elements
print(myarr2.shape) 

(1, 1, 1, 1, 4)
(1, 5)


In [18]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# x = arr4.reshape(2, 4)  # Changes from 1 dimensional to 2 dimensional array
# x = arr4.reshape(2, 5)  # Generates error if elements required for reshaping and actual elements are not equal
x = arr4.reshape(2, 2, 2)  # Changes from 1 dimensional to 3 dimensional array
y = x.reshape(-1)  # Changes to 1-dimensional array. It returns the view of the original array so, the changes made in the new array affects the original array.
print(arr4)
print()
# print(x)
# print(y)
print(arr4.reshape(-1, 4))  # Numpy will assign one of the dimension. Here "-1" is the unknown dimension
print()
print(arr4.reshape(-1, 2))
# print(arr4.reshape(-1, -1))  # We cannot pass two unknown dimension
print()
print(arr4.reshape(-1, 1))

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [19]:
a1 = np.arange(6).reshape(2, 3)   
print(a1)
print()
b1 = a1.flatten()  # Changes any dimensional array into 1-dimension.
print(b1)
print()
b1[2] = 25
print(a1)  # "flatten()" returns the copy of the original array. So, the changes made in the new array does not affect the original array.
print()
print(b1)

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]

[ 0  1 25  3  4  5]


In [20]:
a2 = np.arange(6).reshape(2, 3)   
print(a2)
print()
b2 = a2.ravel()  # Changes any dimensional array into 1-dimension.
print(b2)
print()
b2[2] = 25
print(a2)  # "ravel()" returns the view of the original array. So, the changes made in the new array affects the original array.
print()
print(b2)

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5]

[[ 0  1 25]
 [ 3  4  5]]

[ 0  1 25  3  4  5]


In [21]:
print(a2)
# b3 = np.flip(a2)  # Reverses the order of the array
# b3 = np.fliplr(a2)  # Reverses the order of column while keeping the rows preserved
b3 = np.flipud(a2)  # Reverses the order of rows while keeping the columns preserved
print()
print(b3)

[[ 0  1 25]
 [ 3  4  5]]

[[ 3  4  5]
 [ 0  1 25]]
